### ISSUE TITLE
UPDATE: Document the new Form Settings Importer/Exporter

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Docs#106]
**URL:** https://givewp.com/documentation/core/give-forms/importing-and-exporting-forms/

**PROBLEM:** The doc currently suggests using the WordPress Importer. @ravinderk and the dev team are making a form settings Migration tool that will replace the need for the WordPress importer. This will need to be documented.

**SOLUTION:** Create a new doc walking through the new form/settings migration tool.

**Comment by samsmith89** [comment]
I have been updating this information to be put into 
https://givewp.com/documentation/core/tools/import/import-donations/
The changes are live.

Do I also need to update this page or can it be removed once the /import-donations/ page is updated to reflect the importing of forms?

Since this ability lives in the importer should it just be highlighted there?

It may also be beneficial to let the donor know from the backend that they can upload forms using the importer.
